import type { SimulationState, OutputMode, GeneratedFrame, SignalIntegrity, DashboardWidget } from './simulation';
import type { WidgetType } from './field';
import type { FrameProfile } from './protocol';
import type { Scenario } from './scenario';
import type { ErrorType } from './scenario';
import type { Trigger } from './trigger';
import type { ResponderRule } from './responder';
import type { ValidationTarget } from './validation';

export interface SimulationContextType {
  state: SimulationState;
  start: (profile: FrameProfile, scenario: Scenario | null, outputMode: OutputMode) => void;
  stop: () => void;
  pause: () => void;
  resume: (profile: FrameProfile, scenario: Scenario | null) => void;
  overrideField: (fieldId: string, value: number) => void;
  overrideBit: (bitKey: string, value: number) => void;
  injectError: (errorType: ErrorType) => void;
  resetOverrides: () => void;
  connectSerial: (portName: string, baudRate: number) => Promise<void>;
  disconnectSerial: () => Promise<void>;
  setProfile: (profileId: string | null) => void;
  setScenario: (scenarioId: string | null) => void;
  setOutputMode: (outputMode: OutputMode) => void;
  setUiVisible: (visible: boolean) => void;
  exportLogs: () => void;
  setProfiles: (profiles: FrameProfile[]) => void;
  connectNetwork: (url: string) => Promise<void>;
  disconnectNetwork: () => void;
  startRecording: () => void;
  stopRecording: () => void;
  saveRecording: (name: string, data: any[]) => void;
  deleteRecording: (id: string) => void;
  refreshRecordings: () => void;
  startPlayback: (data: any) => void;
  getPorts: () => void;
  selectExchange: (exchangeId: string | null) => void;
  setAnalyzerMode: (enabled: boolean) => void;
  setDisplayFilter: (filter: string) => void;
  toggleWatchlist: (fieldName: string) => void;
  saveSnapshot: (frame: GeneratedFrame) => void;
  deleteSnapshot: (frameNumber: number) => void;
  setDiffFrame: (index: 0 | 1, frame: GeneratedFrame | null) => void;
  setTelemetryLayout: (profileId: string, layout: string[]) => void;
  setResponderRules: (rules: ResponderRule[]) => void;
  pausePlayback: () => void;
  resumePlayback: () => void;
  seekPlayback: (index: number) => void;
  stepPlayback: (delta: number) => void;
  setSignalIntegrity: (integrity: Partial<SignalIntegrity>) => void;
  setTriggers: (triggers: Trigger[]) => void;
  addWidget: (type: WidgetType, fieldId: string) => void;
  removeWidget: (id: string) => void;
  updateLayout: (widgets: DashboardWidget[]) => void;
  startValidation: (config: { name: string; deviceId: string; operator: string; targets: ValidationTarget[] }) => void;
  stopValidation: () => void;
  cancelValidation: () => void;
  deleteValidationSession: (id: string) => void;
}
